// <auto-generated />
using System;
using Bookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookstore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240101000000_InitialPostgreSQLMigration")]
    partial class InitialPostgreSQLMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ---------------------------------------------------------------
            // address
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("addressline1")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("addressline1");

                b.Property<string>("addressline2")
                    .HasColumnType("text")
                    .HasColumnName("addressline2");

                b.Property<string>("city")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("city");

                b.Property<string>("country")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("country");

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("customerid")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<int>("isactive")
                    .HasColumnType("integer")
                    .HasColumnName("isactive");

                b.Property<string>("state")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("state");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("zipcode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("zipcode");

                b.HasKey("id")
                    .HasName("PK_address");

                b.HasIndex("customerid")
                    .HasDatabaseName("IX_address_customerid");

                b.ToTable("address", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // author
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Authors.Author", b =>
            {
                b.Property<int>("businessentityid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("businessentityid")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<DateTime>("birthdate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("birthdate");

                b.Property<string>("gender")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("gender");

                b.Property<DateTime>("hiredate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("hiredate");

                b.Property<string>("jobtitle")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("jobtitle");

                b.Property<string>("loginid")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("loginid");

                b.Property<string>("maritalstatus")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("maritalstatus");

                b.Property<DateTime>("modifieddate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("modifieddate");

                b.Property<string>("nationalidnumber")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("nationalidnumber");

                b.Property<short>("vacationhours")
                    .HasColumnType("smallint")
                    .HasColumnName("vacationhours");

                b.HasKey("businessentityid")
                    .HasName("PK_author");

                b.ToTable("author", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // book
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<int>("booktypeid")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<int>("conditionid")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("coverimageurl")
                    .HasColumnType("text")
                    .HasColumnName("coverimageurl");

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("genreid")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("isbn")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<decimal>("price")
                    .HasColumnType("numeric")
                    .HasColumnName("price");

                b.Property<int>("publisherid")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<int>("quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<string>("summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int?>("year")
                    .HasColumnType("integer")
                    .HasColumnName("year");

                b.HasKey("id")
                    .HasName("PK_book");

                b.HasIndex("booktypeid")
                    .HasDatabaseName("IX_book_booktypeid");

                b.HasIndex("conditionid")
                    .HasDatabaseName("IX_book_conditionid");

                b.HasIndex("genreid")
                    .HasDatabaseName("IX_book_genreid");

                b.HasIndex("publisherid")
                    .HasDatabaseName("IX_book_publisherid");

                b.ToTable("book", "bobsbookstore_dbo");

                b.HasData(
                    new { id = 1, name = "2020: The Apocalypse",     author = "Li Juan",        isbn = "6556784356", publisherid = 15, booktypeid = 1, genreid = 13, conditionid = 5, coverimageurl = "/images/coverimages/apocalypse.png",        price = 10.95m,  quantity = 25, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 2, name = "Children Of Iron",         author = "Nikki Wolf",     isbn = "7665438976", publisherid = 16, booktypeid = 1, genreid = 11, conditionid = 6, coverimageurl = "/images/coverimages/childrenofiron.png",     price = 13.95m,  quantity =  3, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 3, name = "Gold In The Dark",         author = "Richard Roe",    isbn = "5442280765", publisherid = 17, booktypeid = 1, genreid = 13, conditionid = 5, coverimageurl = "/images/coverimages/goldinthedark.png",      price =  6.50m,  quantity = 10, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 4, name = "Leagues Of Smoke",         author = "Pat Candella",   isbn = "4556789542", publisherid = 18, booktypeid = 2, genreid = 11, conditionid = 7, coverimageurl = "/images/coverimages/leaguesofsmoke.png",     price =  3.00m,  quantity =  1, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 5, name = "Alone With The Stars",     author = "Carlos Salazar", isbn = "4563358087", publisherid = 19, booktypeid = 2, genreid = 12, conditionid = 5, coverimageurl = "/images/coverimages/alonewiththestars.png",  price = 15.95m,  quantity =  5, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 6, name = "The Girl In The Polaroid", author = "Terri Whitlock", isbn = "2354435678", publisherid = 20, booktypeid = 1, genreid = 12, conditionid = 6, coverimageurl = "/images/coverimages/girlinthepolaroid.png", price =  8.25m,  quantity =  2, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 7, name = "1001 Jokes",               author = "Mary Major",     isbn = "6554789632", publisherid = 21, booktypeid = 2, genreid = 11, conditionid = 5, coverimageurl = "/images/coverimages/1001jokes.png",          price = 13.95m,  quantity =  7, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 8, name = "My Search For Meaning",    author = "Mateo Jackson",  isbn = "4558786554", publisherid = 22, booktypeid = 3, genreid =  8, conditionid = 7, coverimageurl = "/images/coverimages/mysearchformeaning.png", price =  5.00m,  quantity = 15, createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) }
                );
            });

            // ---------------------------------------------------------------
            // customer
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Customers.Customer", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime?>("dateofbirth")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("dateofbirth");

                b.Property<string>("email")
                    .HasColumnType("text")
                    .HasColumnName("email");

                b.Property<string>("firstname")
                    .HasColumnType("text")
                    .HasColumnName("firstname");

                b.Property<string>("lastname")
                    .HasColumnType("text")
                    .HasColumnName("lastname");

                b.Property<string>("phone")
                    .HasColumnType("text")
                    .HasColumnName("phone");

                b.Property<string>("sub")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("sub");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("username")
                    .HasColumnType("text")
                    .HasColumnName("username");

                b.HasKey("id")
                    .HasName("PK_customer");

                b.HasIndex("sub")
                    .IsUnique()
                    .HasDatabaseName("IX_customer_sub");

                b.ToTable("customer", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // offer
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<decimal>("bookprice")
                    .HasColumnType("numeric")
                    .HasColumnName("bookprice");

                b.Property<string>("bookname")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("bookname");

                b.Property<int>("booktypeid")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<string>("comment")
                    .HasColumnType("text")
                    .HasColumnName("comment");

                b.Property<int>("conditionid")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("customerid")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<string>("fronturl")
                    .HasColumnType("text")
                    .HasColumnName("fronturl");

                b.Property<int>("genreid")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("isbn")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<int>("offerstatus")
                    .HasColumnType("integer")
                    .HasColumnName("offerstatus");

                b.Property<int>("publisherid")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<string>("summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("id")
                    .HasName("PK_offer");

                b.HasIndex("booktypeid")
                    .HasDatabaseName("IX_offer_booktypeid");

                b.HasIndex("conditionid")
                    .HasDatabaseName("IX_offer_conditionid");

                b.HasIndex("customerid")
                    .HasDatabaseName("IX_offer_customerid");

                b.HasIndex("genreid")
                    .HasDatabaseName("IX_offer_genreid");

                b.HasIndex("publisherid")
                    .HasDatabaseName("IX_offer_publisherid");

                b.ToTable("offer", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Order
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("addressid")
                    .HasColumnType("integer")
                    .HasColumnName("addressid");

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("customerid")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<DateTime>("deliverydate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("deliverydate");

                b.Property<int>("orderstatus")
                    .HasColumnType("integer")
                    .HasColumnName("orderstatus");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("id")
                    .HasName("PK_Order");

                b.HasIndex("addressid")
                    .HasDatabaseName("IX_Order_addressid");

                b.HasIndex("customerid")
                    .HasDatabaseName("IX_Order_customerid");

                b.ToTable("Order", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // orderitem
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("bookid")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("orderid")
                    .HasColumnType("integer")
                    .HasColumnName("orderid");

                b.Property<int>("quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("id")
                    .HasName("PK_orderitem");

                b.HasIndex("bookid")
                    .HasDatabaseName("IX_orderitem_bookid");

                b.HasIndex("orderid")
                    .HasDatabaseName("IX_orderitem_orderid");

                b.ToTable("orderitem", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // product
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Products.Product", b =>
            {
                b.Property<int>("productid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("productid")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("name")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("name");

                b.Property<string>("productnumber")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("productnumber");

                b.Property<int>("safetystocklevel")
                    .HasColumnType("integer")
                    .HasColumnName("safetystocklevel");

                b.HasKey("productid")
                    .HasName("PK_product");

                b.ToTable("product", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // referencedata
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.ReferenceData.ReferenceDataItem", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("datatype")
                    .HasColumnType("integer")
                    .HasColumnName("datatype");

                b.Property<string>("text")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("text");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("id")
                    .HasName("PK_referencedata");

                b.ToTable("referencedata", "bobsbookstore_dbo");

                b.HasData(
                    new { id = 1,  datatype = 2, text = "Hardcover",                  createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 2,  datatype = 2, text = "Trade Paperback",             createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 3,  datatype = 2, text = "Mass Market Paperback",       createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 4,  datatype = 1, text = "New",                         createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 5,  datatype = 1, text = "Like New",                    createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 6,  datatype = 1, text = "Good",                        createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 7,  datatype = 1, text = "Acceptable",                  createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 8,  datatype = 3, text = "Biographies",                 createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 9,  datatype = 3, text = "Children's Books",            createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 10, datatype = 3, text = "History",                     createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 11, datatype = 3, text = "Literature & Fiction",        createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 12, datatype = 3, text = "Mystery, Thriller & Suspense",createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 13, datatype = 3, text = "Science Fiction & Fantasy",   createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 14, datatype = 3, text = "Travel",                      createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 15, datatype = 0, text = "Arcadia Books",               createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 16, datatype = 0, text = "Astral Publishing",           createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 17, datatype = 0, text = "Moonlight Publishing",        createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 18, datatype = 0, text = "Dreamscape Press",            createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 19, datatype = 0, text = "Enchanted Library",           createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 20, datatype = 0, text = "Fantasia House",              createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 21, datatype = 0, text = "Horizon Books",               createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 22, datatype = 0, text = "Infinity Press",              createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 23, datatype = 0, text = "Paradigm Publishing",         createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { id = 24, datatype = 0, text = "Aurora Publishing",           createdby = "System", createdon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), updatedon = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) }
                );
            });

            // ---------------------------------------------------------------
            // shoppingcart
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("correlationid")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("correlationid");

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("id")
                    .HasName("PK_shoppingcart");

                b.ToTable("shoppingcart", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // shoppingcartitem
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("bookid")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("createdby")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("createdon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<int>("shoppingcartid")
                    .HasColumnType("integer")
                    .HasColumnName("shoppingcartid");

                b.Property<DateTime>("updatedon")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int>("wanttobuy")
                    .HasColumnType("integer")
                    .HasColumnName("wanttobuy");

                b.HasKey("id")
                    .HasName("PK_shoppingcartitem");

                b.HasIndex("bookid")
                    .HasDatabaseName("IX_shoppingcartitem_bookid");

                b.HasIndex("shoppingcartid")
                    .HasDatabaseName("IX_shoppingcartitem_shoppingcartid");

                b.ToTable("shoppingcartitem", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Relationships
            // ---------------------------------------------------------------

            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("customerid")
                    .HasConstraintName("FK_address_customer_customerid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");
            });

            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("booktypeid")
                    .HasConstraintName("FK_book_referencedata_booktypeid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("conditionid")
                    .HasConstraintName("FK_book_referencedata_conditionid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("genreid")
                    .HasConstraintName("FK_book_referencedata_genreid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("publisherid")
                    .HasConstraintName("FK_book_referencedata_publisherid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("bookid")
                    .HasConstraintName("FK_shoppingcartitem_book_bookid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Carts.ShoppingCart", "ShoppingCart")
                    .WithMany("ShoppingCartItems")
                    .HasForeignKey("shoppingcartid")
                    .HasConstraintName("FK_shoppingcartitem_shoppingcart_shoppingcartid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Book");
                b.Navigation("ShoppingCart");
            });

            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("customerid")
                    .HasConstraintName("FK_offer_customer_customerid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("booktypeid")
                    .HasConstraintName("FK_offer_referencedata_booktypeid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("conditionid")
                    .HasConstraintName("FK_offer_referencedata_conditionid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("genreid")
                    .HasConstraintName("FK_offer_referencedata_genreid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("publisherid")
                    .HasConstraintName("FK_offer_referencedata_publisherid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Customer");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.HasOne("Bookstore.Domain.Addresses.Address", "Address")
                    .WithMany()
                    .HasForeignKey("addressid")
                    .HasConstraintName("FK_Order_address_addressid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("customerid")
                    .HasConstraintName("FK_Order_customer_customerid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Address");
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("bookid")
                    .HasConstraintName("FK_orderitem_book_bookid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Orders.Order", "Order")
                    .WithMany()
                    .HasForeignKey("orderid")
                    .HasConstraintName("FK_orderitem_Order_orderid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Book");
                b.Navigation("Order");
            });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Navigation("ShoppingCartItems");
            });
#pragma warning restore 612, 618
        }
    }
}