// <auto-generated />
using System;
using Bookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookstore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ---------------------------------------------------------------
            // Address
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("AddressLine1")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("addressline1");

                b.Property<string>("AddressLine2")
                    .HasColumnType("text")
                    .HasColumnName("addressline2");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("city");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("country");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<int>("IsActive")
                    .HasColumnType("integer")
                    .HasColumnName("isactive");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("state");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("zipcode");

                b.HasKey("Id");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("ix_address_customerid");

                b.ToTable("address", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Author
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Authors.Author", b =>
            {
                b.Property<int>("BusinessEntityID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("businessentityid")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("birthdate");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("gender");

                b.Property<DateTime>("HireDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("hiredate");

                b.Property<string>("JobTitle")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("jobtitle");

                b.Property<string>("LoginID")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("loginid");

                b.Property<string>("MaritalStatus")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("maritalstatus");

                b.Property<DateTime>("ModifiedDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("modifieddate");

                b.Property<string>("NationalIDNumber")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("nationalidnumber");

                b.Property<short>("VacationHours")
                    .HasColumnType("smallint")
                    .HasColumnName("vacationhours");

                b.HasKey("BusinessEntityID");

                b.ToTable("author", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Book
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<int>("BookTypeId")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<int>("ConditionId")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("CoverImageUrl")
                    .HasColumnType("text")
                    .HasColumnName("coverimageurl");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("GenreId")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("price");

                b.Property<int>("PublisherId")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<string>("Summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int?>("Year")
                    .HasColumnType("integer")
                    .HasColumnName("year");

                b.HasKey("Id");

                b.HasIndex("BookTypeId")
                    .HasDatabaseName("ix_book_booktypeid");

                b.HasIndex("ConditionId")
                    .HasDatabaseName("ix_book_conditionid");

                b.HasIndex("GenreId")
                    .HasDatabaseName("ix_book_genreid");

                b.HasIndex("PublisherId")
                    .HasDatabaseName("ix_book_publisherid");

                b.ToTable("book", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Customer
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Customers.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime?>("DateOfBirth")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("dateofbirth");

                b.Property<string>("Email")
                    .HasColumnType("text")
                    .HasColumnName("email");

                b.Property<string>("FirstName")
                    .HasColumnType("text")
                    .HasColumnName("firstname");

                b.Property<string>("LastName")
                    .HasColumnType("text")
                    .HasColumnName("lastname");

                b.Property<string>("Phone")
                    .HasColumnType("text")
                    .HasColumnName("phone");

                b.Property<string>("Sub")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("sub");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("Username")
                    .HasColumnType("text")
                    .HasColumnName("username");

                b.HasKey("Id");

                b.HasIndex("Sub")
                    .IsUnique()
                    .HasDatabaseName("ix_customer_sub");

                b.ToTable("customer", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Offer
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<decimal>("BookPrice")
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("bookprice");

                b.Property<int>("BookTypeId")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<string>("BookName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("bookname");

                b.Property<string>("Comment")
                    .HasColumnType("text")
                    .HasColumnName("comment");

                b.Property<int>("ConditionId")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<string>("FrontUrl")
                    .HasColumnType("text")
                    .HasColumnName("fronturl");

                b.Property<int>("GenreId")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<int>("OfferStatus")
                    .HasColumnType("integer")
                    .HasColumnName("offerstatus");

                b.Property<int>("PublisherId")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<string>("Summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");

                b.HasIndex("BookTypeId")
                    .HasDatabaseName("ix_offer_booktypeid");

                b.HasIndex("ConditionId")
                    .HasDatabaseName("ix_offer_conditionid");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("ix_offer_customerid");

                b.HasIndex("GenreId")
                    .HasDatabaseName("ix_offer_genreid");

                b.HasIndex("PublisherId")
                    .HasDatabaseName("ix_offer_publisherid");

                b.ToTable("offer", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Order
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("AddressId")
                    .HasColumnType("integer")
                    .HasColumnName("addressid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<DateTime>("DeliveryDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("deliverydate");

                b.Property<int>("OrderStatus")
                    .HasColumnType("integer")
                    .HasColumnName("orderstatus");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");

                b.HasIndex("AddressId")
                    .HasDatabaseName("ix_order_addressid");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("ix_order_customerid");

                b.ToTable("Order", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // OrderItem
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("BookId")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("OrderId")
                    .HasColumnType("integer")
                    .HasColumnName("orderid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");

                b.HasIndex("BookId")
                    .HasDatabaseName("ix_orderitem_bookid");

                b.HasIndex("OrderId")
                    .HasDatabaseName("ix_orderitem_orderid");

                b.ToTable("orderitem", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Product
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Products.Product", b =>
            {
                b.Property<int>("ProductID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("productid")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("name");

                b.Property<string>("ProductNumber")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("productnumber");

                b.Property<int>("SafetyStockLevel")
                    .HasColumnType("integer")
                    .HasColumnName("safetystocklevel");

                b.HasKey("ProductID");

                b.ToTable("product", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // ReferenceDataItem
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.ReferenceData.ReferenceDataItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("DataType")
                    .HasColumnType("integer")
                    .HasColumnName("datatype");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("text");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");

                b.ToTable("referencedata", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // ShoppingCart
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("CorrelationId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("correlationid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");

                b.ToTable("shoppingcart", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // ShoppingCartItem
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("BookId")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<int>("ShoppingCartId")
                    .HasColumnType("integer")
                    .HasColumnName("shoppingcartid");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int>("WantToBuy")
                    .HasColumnType("integer")
                    .HasColumnName("wanttobuy");

                b.HasKey("Id");

                b.HasIndex("BookId")
                    .HasDatabaseName("ix_shoppingcartitem_bookid");

                b.HasIndex("ShoppingCartId")
                    .HasDatabaseName("ix_shoppingcartitem_shoppingcartid");

                b.ToTable("shoppingcartitem", "bobsbookstore_dbo");
            });

            // ---------------------------------------------------------------
            // Relationship configurations
            // ---------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");
            });

            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("BookTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("ConditionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("GenreId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("PublisherId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("BookTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("ConditionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("GenreId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("PublisherId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Customer");
                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.HasOne("Bookstore.Domain.Addresses.Address", "Address")
                    .WithMany()
                    .HasForeignKey("AddressId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Address");
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("BookId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Orders.Order", "Order")
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Book");
                b.Navigation("Order");
            });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("BookId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Carts.ShoppingCart", "ShoppingCart")
                    .WithMany("ShoppingCartItems")
                    .HasForeignKey("ShoppingCartId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Book");
                b.Navigation("ShoppingCart");
            });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Navigation("ShoppingCartItems");
            });
#pragma warning restore 612, 618
        }
    }
}
