// <auto-generated />
using System;
using Bookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookstore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // -----------------------------------------------------------------------
            // Address
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("AddressLine1")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("addressline1");

                b.Property<string>("AddressLine2")
                    .HasColumnType("text")
                    .HasColumnName("addressline2");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("city");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("country");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<int>("IsActive")
                    .HasColumnType("integer")
                    .HasColumnName("isactive");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("state");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("zipcode");

                b.HasKey("Id");
                b.HasIndex("CustomerId").HasDatabaseName("IX_address_customerid");
                b.ToTable("address", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // Author
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Authors.Author", b =>
            {
                b.Property<int>("BusinessEntityID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("businessentityid")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("birthdate");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("gender");

                b.Property<DateTime>("HireDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("hiredate");

                b.Property<string>("JobTitle")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("jobtitle");

                b.Property<string>("LoginID")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("loginid");

                b.Property<string>("MaritalStatus")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("maritalstatus");

                b.Property<DateTime>("ModifiedDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("modifieddate");

                b.Property<string>("NationalIDNumber")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("nationalidnumber");

                b.Property<short>("VacationHours")
                    .HasColumnType("smallint")
                    .HasColumnName("vacationhours");

                b.HasKey("BusinessEntityID");
                b.ToTable("author", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // Book
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<int>("BookTypeId")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<int>("ConditionId")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("CoverImageUrl")
                    .HasColumnType("text")
                    .HasColumnName("coverimageurl");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("GenreId")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("price");

                b.Property<int>("PublisherId")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<string>("Summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int?>("Year")
                    .HasColumnType("integer")
                    .HasColumnName("year");

                b.HasKey("Id");
                b.HasIndex("BookTypeId").HasDatabaseName("IX_book_booktypeid");
                b.HasIndex("ConditionId").HasDatabaseName("IX_book_conditionid");
                b.HasIndex("GenreId").HasDatabaseName("IX_book_genreid");
                b.HasIndex("PublisherId").HasDatabaseName("IX_book_publisherid");
                b.ToTable("book", "bobsbookstore_dbo");

                b.HasData(
                    new { Id = 1, Author = "Li Juan",        Name = "2020: The Apocalypse",     ISBN = "6556784356", PublisherId = 15, BookTypeId = 1, GenreId = 13, ConditionId = 5, Price = 10.95m,  Quantity = 25, CoverImageUrl = "/images/coverimages/apocalypse.png",        CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 2, Author = "Nikki Wolf",     Name = "Children Of Iron",         ISBN = "7665438976", PublisherId = 16, BookTypeId = 1, GenreId = 11, ConditionId = 6, Price = 13.95m,  Quantity =  3, CoverImageUrl = "/images/coverimages/childrenofiron.png",    CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 3, Author = "Richard Roe",    Name = "Gold In The Dark",         ISBN = "5442280765", PublisherId = 17, BookTypeId = 1, GenreId = 13, ConditionId = 5, Price =  6.50m,  Quantity = 10, CoverImageUrl = "/images/coverimages/goldinthedark.png",     CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 4, Author = "Pat Candella",   Name = "Leagues Of Smoke",         ISBN = "4556789542", PublisherId = 18, BookTypeId = 2, GenreId = 11, ConditionId = 7, Price =  3.00m,  Quantity =  1, CoverImageUrl = "/images/coverimages/leaguesofsmoke.png",    CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 5, Author = "Carlos Salazar", Name = "Alone With The Stars",     ISBN = "4563358087", PublisherId = 19, BookTypeId = 2, GenreId = 12, ConditionId = 5, Price = 15.95m,  Quantity =  5, CoverImageUrl = "/images/coverimages/alonewiththestars.png",  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 6, Author = "Terri Whitlock", Name = "The Girl In The Polaroid", ISBN = "2354435678", PublisherId = 20, BookTypeId = 1, GenreId = 12, ConditionId = 6, Price =  8.25m,  Quantity =  2, CoverImageUrl = "/images/coverimages/girlinthepolaroid.png", CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 7, Author = "Mary Major",     Name = "1001 Jokes",               ISBN = "6554789632", PublisherId = 21, BookTypeId = 2, GenreId = 11, ConditionId = 5, Price = 13.95m,  Quantity =  7, CoverImageUrl = "/images/coverimages/1001jokes.png",         CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 8, Author = "Mateo Jackson",  Name = "My Search For Meaning",   ISBN = "4558786554", PublisherId = 22, BookTypeId = 3, GenreId =  8, ConditionId = 7, Price =  5.00m,  Quantity = 15, CoverImageUrl = "/images/coverimages/mysearchformeaning.png", CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) }
                );
            });

            // -----------------------------------------------------------------------
            // Customer
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Customers.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime?>("DateOfBirth")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("dateofbirth");

                b.Property<string>("Email")
                    .HasColumnType("text")
                    .HasColumnName("email");

                b.Property<string>("FirstName")
                    .HasColumnType("text")
                    .HasColumnName("firstname");

                b.Property<string>("LastName")
                    .HasColumnType("text")
                    .HasColumnName("lastname");

                b.Property<string>("Phone")
                    .HasColumnType("text")
                    .HasColumnName("phone");

                b.Property<string>("Sub")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("sub");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("Username")
                    .HasColumnType("text")
                    .HasColumnName("username");

                b.HasKey("Id");
                b.HasIndex("Sub").IsUnique().HasDatabaseName("IX_customer_sub");
                b.ToTable("customer", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // Offer
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<decimal>("BookPrice")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("bookprice");

                b.Property<string>("BookName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("bookname");

                b.Property<int>("BookTypeId")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<string>("Comment")
                    .HasColumnType("text")
                    .HasColumnName("comment");

                b.Property<int>("ConditionId")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<string>("FrontUrl")
                    .HasColumnType("text")
                    .HasColumnName("fronturl");

                b.Property<int>("GenreId")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<int>("OfferStatus")
                    .HasColumnType("integer")
                    .HasColumnName("offerstatus");

                b.Property<int>("PublisherId")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<string>("Summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");
                b.HasIndex("BookTypeId").HasDatabaseName("IX_offer_booktypeid");
                b.HasIndex("ConditionId").HasDatabaseName("IX_offer_conditionid");
                b.HasIndex("CustomerId").HasDatabaseName("IX_offer_customerid");
                b.HasIndex("GenreId").HasDatabaseName("IX_offer_genreid");
                b.HasIndex("PublisherId").HasDatabaseName("IX_offer_publisherid");
                b.ToTable("offer", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // Order
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("AddressId")
                    .HasColumnType("integer")
                    .HasColumnName("addressid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<DateTime>("DeliveryDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("deliverydate");

                b.Property<int>("OrderStatus")
                    .HasColumnType("integer")
                    .HasColumnName("orderstatus");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");
                b.HasIndex("AddressId").HasDatabaseName("IX_Order_addressid");
                b.HasIndex("CustomerId").HasDatabaseName("IX_Order_customerid");
                b.ToTable("Order", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // OrderItem
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("BookId")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("OrderId")
                    .HasColumnType("integer")
                    .HasColumnName("orderid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");
                b.HasIndex("BookId").HasDatabaseName("IX_orderitem_bookid");
                b.HasIndex("OrderId").HasDatabaseName("IX_orderitem_orderid");
                b.ToTable("orderitem", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // Product
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Products.Product", b =>
            {
                b.Property<int>("ProductID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("productid")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("name");

                b.Property<string>("ProductNumber")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("productnumber");

                b.Property<int>("SafetyStockLevel")
                    .HasColumnType("integer")
                    .HasColumnName("safetystocklevel");

                b.HasKey("ProductID");
                b.ToTable("product", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // ReferenceDataItem
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.ReferenceData.ReferenceDataItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("DataType")
                    .HasColumnType("integer")
                    .HasColumnName("datatype");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("text");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");
                b.ToTable("referencedata", "bobsbookstore_dbo");

                b.HasData(
                    new { Id =  1, DataType = 2, Text = "Hardcover",                   CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  2, DataType = 2, Text = "Trade Paperback",              CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  3, DataType = 2, Text = "Mass Market Paperback",        CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  4, DataType = 1, Text = "New",                          CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  5, DataType = 1, Text = "Like New",                     CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  6, DataType = 1, Text = "Good",                         CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  7, DataType = 1, Text = "Acceptable",                   CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  8, DataType = 3, Text = "Biographies",                  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id =  9, DataType = 3, Text = "Children's Books",             CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 10, DataType = 3, Text = "History",                      CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 11, DataType = 3, Text = "Literature & Fiction",         CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 12, DataType = 3, Text = "Mystery, Thriller & Suspense", CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 13, DataType = 3, Text = "Science Fiction & Fantasy",    CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 14, DataType = 3, Text = "Travel",                       CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 15, DataType = 0, Text = "Arcadia Books",                CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 16, DataType = 0, Text = "Astral Publishing",            CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 17, DataType = 0, Text = "Moonlight Publishing",         CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 18, DataType = 0, Text = "Dreamscape Press",             CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 19, DataType = 0, Text = "Enchanted Library",            CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 20, DataType = 0, Text = "Fantasia House",               CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 21, DataType = 0, Text = "Horizon Books",                CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 22, DataType = 0, Text = "Infinity Press",               CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 23, DataType = 0, Text = "Paradigm Publishing",          CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 24, DataType = 0, Text = "Aurora Publishing",            CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) }
                );
            });

            // -----------------------------------------------------------------------
            // ShoppingCart
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("CorrelationId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("correlationid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id");
                b.ToTable("shoppingcart", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // ShoppingCartItem
            // -----------------------------------------------------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("BookId")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<int>("ShoppingCartId")
                    .HasColumnType("integer")
                    .HasColumnName("shoppingcartid");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int>("WantToBuy")
                    .HasColumnType("integer")
                    .HasColumnName("wanttobuy");

                b.HasKey("Id");
                b.HasIndex("BookId").HasDatabaseName("IX_shoppingcartitem_bookid");
                b.HasIndex("ShoppingCartId").HasDatabaseName("IX_shoppingcartitem_shoppingcartid");
                b.ToTable("shoppingcartitem", "bobsbookstore_dbo");
            });

            // -----------------------------------------------------------------------
            // Relationships
            // -----------------------------------------------------------------------

            // Address -> Customer
            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Customer");
            });

            // Book -> ReferenceDataItem (Publisher, BookType, Genre, Condition)
            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("BookTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("ConditionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("GenreId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("PublisherId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            // Offer -> Customer, ReferenceDataItem (x4)
            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("BookTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("ConditionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("GenreId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("PublisherId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Customer");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            // Order -> Customer (Restrict), Address (Cascade)
            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.HasOne("Bookstore.Domain.Addresses.Address", "Address")
                    .WithMany()
                    .HasForeignKey("AddressId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Address");
                b.Navigation("Customer");
            });

            // OrderItem -> Order, Book
            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.HasOne("Bookstore.Domain.Orders.Order", "Order")
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("BookId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Book");
                b.Navigation("Order");
            });

            // ShoppingCartItem -> ShoppingCart, Book
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.HasOne("Bookstore.Domain.Carts.ShoppingCart", "ShoppingCart")
                    .WithMany("ShoppingCartItems")
                    .HasForeignKey("ShoppingCartId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("BookId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Book");
                b.Navigation("ShoppingCart");
            });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Navigation("ShoppingCartItems");
            });
#pragma warning restore 612, 618
        }
    }
}
