// <auto-generated />
using System;
using Bookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookstore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // -------------------------
            // Address
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("AddressLine1")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("addressline1");

                b.Property<string>("AddressLine2")
                    .HasColumnType("text")
                    .HasColumnName("addressline2");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("city");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("country");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<int>("IsActive")
                    .HasColumnType("integer")
                    .HasColumnName("isactive");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("state");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("zipcode");

                b.HasKey("Id")
                    .HasName("PK_address");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("IX_address_customerid");

                b.ToTable("address", "bobsbookstore_dbo");
            });

            // -------------------------
            // Author
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Authors.Author", b =>
            {
                b.Property<int>("BusinessEntityID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("businessentityid");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BusinessEntityID"));

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("birthdate");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("gender");

                b.Property<DateTime>("HireDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("hiredate");

                b.Property<string>("JobTitle")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("jobtitle");

                b.Property<string>("LoginID")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("loginid");

                b.Property<string>("MaritalStatus")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("char(1)")
                    .HasColumnName("maritalstatus");

                b.Property<DateTime>("ModifiedDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("modifieddate");

                b.Property<string>("NationalIDNumber")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("nationalidnumber");

                b.Property<short>("VacationHours")
                    .HasColumnType("smallint")
                    .HasColumnName("vacationhours");

                b.HasKey("BusinessEntityID")
                    .HasName("PK_author");

                b.ToTable("author", "bobsbookstore_dbo");
            });

            // -------------------------
            // Book
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<int>("BookTypeId")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<int>("ConditionId")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("CoverImageUrl")
                    .HasColumnType("text")
                    .HasColumnName("coverimageurl");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("GenreId")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric")
                    .HasColumnName("price");

                b.Property<int>("PublisherId")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<string>("Summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int?>("Year")
                    .HasColumnType("integer")
                    .HasColumnName("year");

                b.HasKey("Id")
                    .HasName("PK_book");

                b.HasIndex("BookTypeId")
                    .HasDatabaseName("IX_book_booktypeid");

                b.HasIndex("ConditionId")
                    .HasDatabaseName("IX_book_conditionid");

                b.HasIndex("GenreId")
                    .HasDatabaseName("IX_book_genreid");

                b.HasIndex("PublisherId")
                    .HasDatabaseName("IX_book_publisherid");

                b.ToTable("book", "bobsbookstore_dbo");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Author = "Li Juan",
                        BookTypeId = 1,
                        ConditionId = 5,
                        CoverImageUrl = "/images/coverimages/apocalypse.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 13,
                        ISBN = "6556784356",
                        Name = "2020: The Apocalypse",
                        Price = 10.95m,
                        PublisherId = 15,
                        Quantity = 25,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 2,
                        Author = "Nikki Wolf",
                        BookTypeId = 1,
                        ConditionId = 6,
                        CoverImageUrl = "/images/coverimages/childrenofiron.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 11,
                        ISBN = "7665438976",
                        Name = "Children Of Iron",
                        Price = 13.95m,
                        PublisherId = 16,
                        Quantity = 3,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 3,
                        Author = "Richard Roe",
                        BookTypeId = 1,
                        ConditionId = 5,
                        CoverImageUrl = "/images/coverimages/goldinthedark.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 13,
                        ISBN = "5442280765",
                        Name = "Gold In The Dark",
                        Price = 6.50m,
                        PublisherId = 17,
                        Quantity = 10,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 4,
                        Author = "Pat Candella",
                        BookTypeId = 2,
                        ConditionId = 7,
                        CoverImageUrl = "/images/coverimages/leaguesofsmoke.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 11,
                        ISBN = "4556789542",
                        Name = "Leagues Of Smoke",
                        Price = 3.00m,
                        PublisherId = 18,
                        Quantity = 1,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 5,
                        Author = "Carlos Salazar",
                        BookTypeId = 2,
                        ConditionId = 5,
                        CoverImageUrl = "/images/coverimages/alonewiththestars.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 12,
                        ISBN = "4563358087",
                        Name = "Alone With The Stars",
                        Price = 15.95m,
                        PublisherId = 19,
                        Quantity = 5,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 6,
                        Author = "Terri Whitlock",
                        BookTypeId = 1,
                        ConditionId = 6,
                        CoverImageUrl = "/images/coverimages/girlinthepolaroid.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 12,
                        ISBN = "2354435678",
                        Name = "The Girl In The Polaroid",
                        Price = 8.25m,
                        PublisherId = 20,
                        Quantity = 2,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 7,
                        Author = "Mary Major",
                        BookTypeId = 2,
                        ConditionId = 5,
                        CoverImageUrl = "/images/coverimages/1001jokes.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 11,
                        ISBN = "6554789632",
                        Name = "1001 Jokes",
                        Price = 13.95m,
                        PublisherId = 21,
                        Quantity = 7,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 8,
                        Author = "Mateo Jackson",
                        BookTypeId = 3,
                        ConditionId = 7,
                        CoverImageUrl = "/images/coverimages/mysearchformeaning.png",
                        CreatedBy = "System",
                        CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        GenreId = 8,
                        ISBN = "4558786554",
                        Name = "My Search For Meaning",
                        Price = 5.00m,
                        PublisherId = 22,
                        Quantity = 15,
                        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    });
            });

            // -------------------------
            // Customer
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Customers.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime?>("DateOfBirth")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("dateofbirth");

                b.Property<string>("Email")
                    .HasColumnType("text")
                    .HasColumnName("email");

                b.Property<string>("FirstName")
                    .HasColumnType("text")
                    .HasColumnName("firstname");

                b.Property<string>("LastName")
                    .HasColumnType("text")
                    .HasColumnName("lastname");

                b.Property<string>("Phone")
                    .HasColumnType("text")
                    .HasColumnName("phone");

                b.Property<string>("Sub")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("sub");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<string>("Username")
                    .HasColumnType("text")
                    .HasColumnName("username");

                b.HasKey("Id")
                    .HasName("PK_customer");

                b.HasIndex("Sub")
                    .IsUnique()
                    .HasDatabaseName("IX_customer_sub");

                b.ToTable("customer", "bobsbookstore_dbo");
            });

            // -------------------------
            // Offer
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Author")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("author");

                b.Property<decimal>("BookPrice")
                    .HasColumnType("numeric")
                    .HasColumnName("bookprice");

                b.Property<int>("BookTypeId")
                    .HasColumnType("integer")
                    .HasColumnName("booktypeid");

                b.Property<string>("BookName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("bookname");

                b.Property<string>("Comment")
                    .HasColumnType("text")
                    .HasColumnName("comment");

                b.Property<int>("ConditionId")
                    .HasColumnType("integer")
                    .HasColumnName("conditionid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<string>("FrontUrl")
                    .HasColumnType("text")
                    .HasColumnName("fronturl");

                b.Property<int>("GenreId")
                    .HasColumnType("integer")
                    .HasColumnName("genreid");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("isbn");

                b.Property<int>("OfferStatus")
                    .HasColumnType("integer")
                    .HasColumnName("offerstatus");

                b.Property<int>("PublisherId")
                    .HasColumnType("integer")
                    .HasColumnName("publisherid");

                b.Property<string>("Summary")
                    .HasColumnType("text")
                    .HasColumnName("summary");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id")
                    .HasName("PK_offer");

                b.HasIndex("BookTypeId")
                    .HasDatabaseName("IX_offer_booktypeid");

                b.HasIndex("ConditionId")
                    .HasDatabaseName("IX_offer_conditionid");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("IX_offer_customerid");

                b.HasIndex("GenreId")
                    .HasDatabaseName("IX_offer_genreid");

                b.HasIndex("PublisherId")
                    .HasDatabaseName("IX_offer_publisherid");

                b.ToTable("offer", "bobsbookstore_dbo");
            });

            // -------------------------
            // Order
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("AddressId")
                    .HasColumnType("integer")
                    .HasColumnName("addressid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("CustomerId")
                    .HasColumnType("integer")
                    .HasColumnName("customerid");

                b.Property<DateTime>("DeliveryDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("deliverydate");

                b.Property<int>("OrderStatus")
                    .HasColumnType("integer")
                    .HasColumnName("orderstatus");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id")
                    .HasName("PK_Order");

                b.HasIndex("AddressId")
                    .HasDatabaseName("IX_Order_addressid");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("IX_Order_customerid");

                b.ToTable("Order", "bobsbookstore_dbo");
            });

            // -------------------------
            // OrderItem
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("BookId")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("OrderId")
                    .HasColumnType("integer")
                    .HasColumnName("orderid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id")
                    .HasName("PK_orderitem");

                b.HasIndex("BookId")
                    .HasDatabaseName("IX_orderitem_bookid");

                b.HasIndex("OrderId")
                    .HasDatabaseName("IX_orderitem_orderid");

                b.ToTable("orderitem", "bobsbookstore_dbo");
            });

            // -------------------------
            // Product
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Products.Product", b =>
            {
                b.Property<int>("ProductID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("productid");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("name");

                b.Property<string>("ProductNumber")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)")
                    .HasColumnName("productnumber");

                b.Property<int>("SafetyStockLevel")
                    .HasColumnType("integer")
                    .HasColumnName("safetystocklevel");

                b.HasKey("ProductID")
                    .HasName("PK_product");

                b.ToTable("product", "bobsbookstore_dbo");
            });

            // -------------------------
            // ReferenceDataItem
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.ReferenceData.ReferenceDataItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("DataType")
                    .HasColumnType("integer")
                    .HasColumnName("datatype");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("text");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id")
                    .HasName("PK_referencedata");

                b.ToTable("referencedata", "bobsbookstore_dbo");

                b.HasData(
                    new { Id = 1,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 2, Text = "Hardcover",              UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 2,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 2, Text = "Trade Paperback",        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 3,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 2, Text = "Mass Market Paperback",  UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 4,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 1, Text = "New",                   UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 5,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 1, Text = "Like New",              UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 6,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 1, Text = "Good",                  UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 7,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 1, Text = "Acceptable",            UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 8,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 3, Text = "Biographies",           UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 9,  CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 3, Text = "Children's Books",      UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 10, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 3, Text = "History",               UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 11, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 3, Text = "Literature & Fiction",  UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 12, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 3, Text = "Mystery, Thriller & Suspense", UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 13, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 3, Text = "Science Fiction & Fantasy", UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 14, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 3, Text = "Travel",                UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 15, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Arcadia Books",         UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 16, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Astral Publishing",     UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 17, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Moonlight Publishing",  UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 18, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Dreamscape Press",      UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 19, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Enchanted Library",     UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 20, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Fantasia House",        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 21, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Horizon Books",         UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 22, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Infinity Press",        UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 23, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Paradigm Publishing",   UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 24, CreatedBy = "System", CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), DataType = 0, Text = "Aurora Publishing",     UpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) });
            });

            // -------------------------
            // ShoppingCart
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("CorrelationId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("correlationid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.HasKey("Id")
                    .HasName("PK_shoppingcart");

                b.ToTable("shoppingcart", "bobsbookstore_dbo");
            });

            // -------------------------
            // ShoppingCartItem
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("BookId")
                    .HasColumnType("integer")
                    .HasColumnName("bookid");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("createdby");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("createdon");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<int>("ShoppingCartId")
                    .HasColumnType("integer")
                    .HasColumnName("shoppingcartid");

                b.Property<DateTime>("UpdatedOn")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("updatedon");

                b.Property<int>("WantToBuy")
                    .HasColumnType("integer")
                    .HasColumnName("wanttobuy");

                b.HasKey("Id")
                    .HasName("PK_shoppingcartitem");

                b.HasIndex("BookId")
                    .HasDatabaseName("IX_shoppingcartitem_bookid");

                b.HasIndex("ShoppingCartId")
                    .HasDatabaseName("IX_shoppingcartitem_shoppingcartid");

                b.ToTable("shoppingcartitem", "bobsbookstore_dbo");
            });

            // -------------------------
            // Relationships
            // -------------------------
            modelBuilder.Entity("Bookstore.Domain.Addresses.Address", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .HasConstraintName("FK_address_customer_customerid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");
            });

            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
            {
                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("BookTypeId")
                    .HasConstraintName("FK_book_referencedata_booktypeid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("ConditionId")
                    .HasConstraintName("FK_book_referencedata_conditionid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("GenreId")
                    .HasConstraintName("FK_book_referencedata_genreid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("PublisherId")
                    .HasConstraintName("FK_book_referencedata_publisherid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            modelBuilder.Entity("Bookstore.Domain.Offers.Offer", b =>
            {
                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .HasConstraintName("FK_offer_customer_customerid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "BookType")
                    .WithMany()
                    .HasForeignKey("BookTypeId")
                    .HasConstraintName("FK_offer_referencedata_booktypeid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Condition")
                    .WithMany()
                    .HasForeignKey("ConditionId")
                    .HasConstraintName("FK_offer_referencedata_conditionid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Genre")
                    .WithMany()
                    .HasForeignKey("GenreId")
                    .HasConstraintName("FK_offer_referencedata_genreid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.ReferenceData.ReferenceDataItem", "Publisher")
                    .WithMany()
                    .HasForeignKey("PublisherId")
                    .HasConstraintName("FK_offer_referencedata_publisherid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BookType");
                b.Navigation("Condition");
                b.Navigation("Customer");
                b.Navigation("Genre");
                b.Navigation("Publisher");
            });

            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.HasOne("Bookstore.Domain.Addresses.Address", "Address")
                    .WithMany()
                    .HasForeignKey("AddressId")
                    .HasConstraintName("FK_Order_address_addressid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Customers.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .HasConstraintName("FK_Order_customer_customerid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Address");
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Bookstore.Domain.Orders.OrderItem", b =>
            {
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("BookId")
                    .HasConstraintName("FK_orderitem_book_bookid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Orders.Order", "Order")
                    .WithMany("orderItems")
                    .HasForeignKey("OrderId")
                    .HasConstraintName("FK_orderitem_Order_orderid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Book");
                b.Navigation("Order");
            });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCartItem", b =>
            {
                b.HasOne("Bookstore.Domain.Books.Book", "Book")
                    .WithMany()
                    .HasForeignKey("BookId")
                    .HasConstraintName("FK_shoppingcartitem_book_bookid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bookstore.Domain.Carts.ShoppingCart", "ShoppingCart")
                    .WithMany("ShoppingCartItems")
                    .HasForeignKey("ShoppingCartId")
                    .HasConstraintName("FK_shoppingcartitem_shoppingcart_shoppingcartid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Book");
                b.Navigation("ShoppingCart");
            });

            modelBuilder.Entity("Bookstore.Domain.Carts.ShoppingCart", b =>
            {
                b.Navigation("ShoppingCartItems");
            });

            modelBuilder.Entity("Bookstore.Domain.Orders.Order", b =>
            {
                b.Navigation("orderItems");
            });
#pragma warning restore 612, 618
        }
    }
}
